/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Dialog;

import com.ridwan.DAO.PerangkatVMDao;
import com.ridwan.Model.PenyebabModel;
import com.ridwan.Model.PerangkatVMModel;
import com.ridwan.TableModel.TablemodelPenyebab;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ciwong
 */
public class DialogAddPenyebab extends javax.swing.JDialog {

    private boolean modeEdit;
    private PenyebabModel pm;
    private PerangkatVMDao perangkatVMDao = new PerangkatVMDao();
    /**
     * Creates new form DialogAddPenyebab
     */
    public DialogAddPenyebab() {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        loadPerangkatvm();
    }
    
    public PenyebabModel insertPenyebab(){
        
        this.modeEdit=false;
        setTitle("Tambah Penyebab");
        setVisible(true);
        setLocationRelativeTo(null);
        loadPerangkatvm();
     return pm;   
    }
    
    private void loadPerangkatvm(){
        List<PerangkatVMModel> pvmmm = perangkatVMDao.getPerangkatVMModels();
        for (PerangkatVMModel p: pvmmm){
            cbo_PerangkatVM.addItem(p);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_namapenyebab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbo_kategori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbo_PerangkatVM = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Penyebab :");

        jLabel2.setText("Kategori :");

        cbo_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- PILIH -", "Aplicatioin System", "Hardware System", "Web & Reporting", "Installation", "Human Resource", "Maintenance System", "Afc Ticketing System", "Migration System", "Other", " " }));

        jLabel3.setText("Part :");

        cbo_PerangkatVM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- PILIH -" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbo_PerangkatVM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_namapenyebab, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_kategori, javax.swing.GroupLayout.Alignment.LEADING, 0, 168, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_namapenyebab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_PerangkatVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/Add_24x24.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
if (modeEdit==false){
    pm = new PenyebabModel();
}


 
if (txt_namapenyebab.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Nama Penyebab Masih Kosong");
}else if (cbo_kategori.getSelectedIndex()==0){
    JOptionPane.showMessageDialog(null, "Kategori Belum Dipilih");
}
else if (cbo_PerangkatVM.getSelectedIndex()==0){
    JOptionPane.showMessageDialog(null, "Perangkat Belum Dipilih");
}
else {
    String nama = txt_namapenyebab.getText();
    String kategori = (String) cbo_kategori.getSelectedItem();
    PerangkatVMModel pvmmodel = (PerangkatVMModel) cbo_PerangkatVM.getSelectedItem();
    
    pm = new PenyebabModel();
    pm.setNamaPenyebab(nama);
    pm.setKategori(kategori);
    pm.setPvmmodel(pvmmodel);
    
    dispose();
    
    
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbo_PerangkatVM;
    private javax.swing.JComboBox cbo_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_namapenyebab;
    // End of variables declaration//GEN-END:variables
}
