/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Frm;

import com.ridwan.DAO.ProjekDao;
import com.ridwan.DAO.TroubleETDao;
import com.ridwan.Model.ProjectModel;
import com.ridwan.Model.TroubleEtModel;
import com.ridwan.TableModel.TableModelExportExcel;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.table.TableModel;
import static org.apache.commons.compress.ArchiveReadTest.data;
import org.apache.commons.compress.utils.IOUtils;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Drawing;
import org.apache.poi.ss.usermodel.Picture;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Muhammad Ridwan
 */
public class ExportbyStatus extends javax.swing.JInternalFrame {

    private TroubleETDao troubleETDao = new TroubleETDao();
    private ProjekDao projekDao = new ProjekDao();
    private TableModelExportExcel tableModelExportExcel = new TableModelExportExcel();
    JTable table = new JTable();
    
    /**
     * Creates new form ExportFrm
     */
    public ExportbyStatus() {
        initComponents();
         setIconifiable(false);
        setMaximizable(false);
        setClosable(false);
        setResizable(false);
        
       ProgressBar.setVisible(false);
       
        table.setModel(tableModelExportExcel);
    }
    
   /*private void loadData(){
        List<TroubleEtModel> export = troubleETDao.getExport((ProjectModel) cbo_projek.getSelectedItem(), txt_tglawal.getDate(), txt_akhir.getDate());
       tableModelExportExcel.setData(export);
   }*/
   
    
    
    
   /* public void exportTable(JTable table, File file) throws IOException {
            TableModel model = table.getModel();
            FileWriter out = new FileWriter(file);
            for(int i=0; i < model.getColumnCount(); i++) {
        out.write(model.getColumnName(i) + "\t");
            }
            out.write("\n");

            for(int i=0; i< model.getRowCount(); i++) {
        for(int j=0; j < model.getColumnCount(); j++) {
            out.write(model.getValueAt(i,j).toString()+"\t");
            }
            out.write("\n");
        }

        out.close();
        System.out.println("write out to: " + file);
}
    */
    
    
    
   
    
    
      public JTextField getTxtPengguna (){
        return txt_petugas;
    }
    
    public void setTxtPengguna (JTextField txtpetugas){
        
    this.txt_petugas = txtpetugas;
    
    }
    
    
    
     /*private void loadProjek(){
        List<ProjectModel> projekModels = projekDao.getProjekModels();
        for (ProjectModel pp : projekModels){
            cbo_projek.addItem(pp);
           // cbo_projekcvm.addItem(pp);
        }
    }
    */
     
     
     
     
     private boolean validasiInput2(){
         boolean valid = false;
         if (txt_tglawal.getDate()==null){
             JOptionPane.showMessageDialog(null, "Tanggal Awal Belum Dipilih");
         }else if (txt_akhir.getDate()==null){
             JOptionPane.showMessageDialog(null, "Tanggal Akhir Belum Dipilih");
         }else {
             valid = true;
         }
         return valid;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tglawal = new com.toedter.calendar.JDateChooser();
        txt_akhir = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_petugas = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txt_terimakasih1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setOpaque(true);

        txt_tglawal.setFocusable(false);
        txt_tglawal.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        txt_akhir.setFocusable(false);
        txt_akhir.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/susu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        txt_petugas.setBackground(new java.awt.Color(0, 255, 255));
        txt_petugas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt_petugas.setForeground(new java.awt.Color(0, 0, 153));
        txt_petugas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_petugas.setBorder(null);
        txt_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_petugasActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jSeparator1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/left-arrow (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Dari Tanggal :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Sampai Tanggal :");

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/calculator.png"))); // NOI18N
        jLabel7.setText("Count Data");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 0, 153));

        jSeparator3.setForeground(new java.awt.Color(0, 255, 255));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("You Can Count Data By Status..");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txt_terimakasih1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txt_terimakasih1.setForeground(new java.awt.Color(0, 51, 153));
        txt_terimakasih1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_terimakasih1.setText("Mohon Persiapkan File Master \"Form Call Center & IT Support Unit.xlsx Untuk Export dan Counting Data ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(txt_tglawal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 686, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addComponent(txt_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_terimakasih1)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(734, 734, 734))))
            .addGroup(layout.createSequentialGroup()
                .addGap(609, 609, 609)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_tglawal, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txt_akhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(txt_terimakasih1)
                .addGap(18, 18, 18)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_petugasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ExportCCForm(){
        List<TroubleEtModel> etModelsbystatus = troubleETDao.getEtExportStatusCC(txt_tglawal.getDate(), txt_akhir.getDate());
    
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
       XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(0);

        for (int r = 34; r<etModelsbystatus.size()+34; r++ ){
             Row row = sheet1.getRow(r);
             for (int c = 10; c<=12; c++){
             if (c==10){
            org.apache.poi.ss.usermodel.Cell column = row.getCell(c);
            String updatename = column.getStringCellValue();
               updatename=String.valueOf(etModelsbystatus.get(r-34).getNamaProjek());
             column.setCellValue(updatename);
           
        }else if (c==11){
              org.apache.poi.ss.usermodel.Cell column1 = row.getCell(c);
        String updatename1 = column1.getStringCellValue();
            updatename1=String.valueOf(etModelsbystatus.get(r-34).getStatus2());
             column1.setCellValue(updatename1);
        }else if (c==12){
              org.apache.poi.ss.usermodel.Cell column2 = row.getCell(c);
        int updatename2 = (int) column2.getNumericCellValue();
            updatename2=Integer.valueOf(etModelsbystatus.get(r-34).getCount());
             column2.setCellValue(updatename2);
        }
       
             }
        
        }
        
        // Get the row of your desired cell.
        // Let's say that your desired cell is at row 2.
       
        //System.out.println(updatename);
         
        //Close the excel file.
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();
          JOptionPane.showMessageDialog(null, "Data Berhasil DiExport ke E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx");

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
        
    }
    
    
    
    
    private void ExportITForm(){
        List<TroubleEtModel> etModelsbystatus = troubleETDao.getEtExportStatusIT(txt_tglawal.getDate(), txt_akhir.getDate());
    
        
         try {
             
     
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
        XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(1);

        for (int r = 34; r<etModelsbystatus.size()+34; r++ ){
             Row row = sheet1.getRow(r);
             for (int c = 10; c<=12; c++){
             if (c==10){
            org.apache.poi.ss.usermodel.Cell column = row.getCell(c);
            String updatename = column.getStringCellValue();
               updatename=String.valueOf(etModelsbystatus.get(r-34).getNamaProjek());
             column.setCellValue(updatename);
           
        }else if (c==11){
              org.apache.poi.ss.usermodel.Cell column1 = row.getCell(c);
        String updatename1 = column1.getStringCellValue();
            updatename1=String.valueOf(etModelsbystatus.get(r-34).getStatus2());
             column1.setCellValue(updatename1);
        }else if (c==12){
              org.apache.poi.ss.usermodel.Cell column2 = row.getCell(c);
        int updatename2 = (int) column2.getNumericCellValue();
            updatename2=Integer.valueOf(etModelsbystatus.get(r-34).getCount());
             column2.setCellValue(updatename2);
        }
       
             }
        
        }
        
        // Get the row of your desired cell.
        // Let's say that your desired cell is at row 2.
       
        //System.out.println(updatename);
         
        //Close the excel file.
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();
          JOptionPane.showMessageDialog(null, "Data Berhasil DiExport ke E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx");

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
        
    }
    
    
    
    
    private void AllDataOpenIT(){
        List<TroubleEtModel> etModelsByStatusandDate = troubleETDao.getcountandalldata("Open","PERMASALAHAN", txt_tglawal.getDate(), txt_akhir.getDate());
    
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
        XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(1);
        
        for (int r=48; r<etModelsByStatusandDate.size()+48; r++){
            Row row = sheet1.getRow(r);
             org.apache.poi.ss.usermodel.Cell column48 = row.getCell(1);
            String updatename = column48.getStringCellValue();
               updatename=String.valueOf("- ("+etModelsByStatusandDate.get(r-48).getProm().getNamaprojek()+") "+etModelsByStatusandDate.get(r-48).getEtm().getNamaPerangkat()+" "+etModelsByStatusandDate.get(r-48).getSm().getNamastasiun()+" "+etModelsByStatusandDate.get(r-48).getPart().getNamaPerangkat()+" ( "+etModelsByStatusandDate.get(r-48).getPm().getNamaPenyebab()+")");
             column48.setCellValue(updatename);
        }
/*
        for (int r = 34; r<etModelsbystatus.size()+34; r++ ){
             Row row = sheet1.getRow(r);
             for (int c = 10; c<=12; c++){
             if (c==10){
            org.apache.poi.ss.usermodel.Cell column = row.getCell(c);
            String updatename = column.getStringCellValue();
               updatename=String.valueOf(etModelsbystatus.get(r-34).getNamaProjek());
             column.setCellValue(updatename);
           
        }else if (c==11){
              org.apache.poi.ss.usermodel.Cell column1 = row.getCell(c);
        String updatename1 = column1.getStringCellValue();
            updatename1=String.valueOf(etModelsbystatus.get(r-34).getStatus2());
             column1.setCellValue(updatename1);
        }else if (c==12){
              org.apache.poi.ss.usermodel.Cell column2 = row.getCell(c);
        int updatename2 = (int) column2.getNumericCellValue();
            updatename2=Integer.valueOf(etModelsbystatus.get(r-34).getCount());
             column2.setCellValue(updatename2);
        }
       
             }
        
        }*/
        
        // Get the row of your desired cell.
        // Let's say that your desired cell is at row 2.
       
        //System.out.println(updatename);
         
        //Close the excel file.
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
    }
    
    
    
    
    
    
    private void AllDataOpenCC(){
        List<TroubleEtModel> etModelsByStatusandDate = troubleETDao.getcountandalldata("Open","ADUAN", txt_tglawal.getDate(), txt_akhir.getDate());
    
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
        XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(0);
        
        for (int r=44; r<etModelsByStatusandDate.size()+44; r++){
            Row row = sheet1.getRow(r);
             org.apache.poi.ss.usermodel.Cell column44 = row.getCell(1);
            String updatename = column44.getStringCellValue();
               updatename=String.valueOf("- ("+etModelsByStatusandDate.get(r-44).getProm().getNamaprojek()+") "+etModelsByStatusandDate.get(r-44).getEtm().getNamaPerangkat()+" "+etModelsByStatusandDate.get(r-44).getSm().getNamastasiun()+" "+etModelsByStatusandDate.get(r-44).getProblem());
             column44.setCellValue(updatename);
        }
/*
        for (int r = 34; r<etModelsbystatus.size()+34; r++ ){
             Row row = sheet1.getRow(r);
             for (int c = 10; c<=12; c++){
             if (c==10){
            org.apache.poi.ss.usermodel.Cell column = row.getCell(c);
            String updatename = column.getStringCellValue();
               updatename=String.valueOf(etModelsbystatus.get(r-34).getNamaProjek());
             column.setCellValue(updatename);
           
        }else if (c==11){
              org.apache.poi.ss.usermodel.Cell column1 = row.getCell(c);
        String updatename1 = column1.getStringCellValue();
            updatename1=String.valueOf(etModelsbystatus.get(r-34).getStatus2());
             column1.setCellValue(updatename1);
        }else if (c==12){
              org.apache.poi.ss.usermodel.Cell column2 = row.getCell(c);
        int updatename2 = (int) column2.getNumericCellValue();
            updatename2=Integer.valueOf(etModelsbystatus.get(r-34).getCount());
             column2.setCellValue(updatename2);
        }
       
             }
        
        }*/
        
        // Get the row of your desired cell.
        // Let's say that your desired cell is at row 2.
       
        //System.out.println(updatename);
         
        //Close the excel file.
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
    }
    
    
   
    
    
       
        private void dateday0(){
        Date d = txt_tglawal.getDate();  
        DateFormat dayFormat = new SimpleDateFormat("EEEE");  
       String day = dayFormat.format(d);
       
        DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");  
       String tanggal = dateFormat.format(d);
    
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
        XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(0);
        
            Row row = sheet1.getRow(3);
             org.apache.poi.ss.usermodel.Cell columnday = row.getCell(1);
            String updatename = columnday.getStringCellValue();
               updatename=String.valueOf("Day : "+day);
             columnday.setCellValue(updatename);
             
              org.apache.poi.ss.usermodel.Cell columndate = row.getCell(2);
            String updatenamedate = columndate.getStringCellValue();
               updatenamedate=String.valueOf("Date : "+tanggal);
             columndate.setCellValue(updatenamedate);
             
             
       
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
        }
        
        
        
        
        
        
         private void dateday1(){
         Date d = txt_tglawal.getDate();   
        DateFormat dayFormat = new SimpleDateFormat("EEEE");  
       String day = dayFormat.format(d);
       
        DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");  
       String tanggal = dateFormat.format(d);
    
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));

        //Get workbook for XLS file.
        XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        XSSFSheet sheet1 = yourworkbook.getSheetAt(1);
        
            Row row = sheet1.getRow(3);
             org.apache.poi.ss.usermodel.Cell columnday = row.getCell(1);
            String updatename = columnday.getStringCellValue();
               updatename=String.valueOf("Day : "+day);
             columnday.setCellValue(updatename);
             
              org.apache.poi.ss.usermodel.Cell columndate = row.getCell(2);
            String updatenamedate = columndate.getStringCellValue();
               updatenamedate=String.valueOf("Date : "+tanggal);
             columndate.setCellValue(updatenamedate);
             
             
       
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xlsx"));
        yourworkbook.write(out);
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
        }
    
    
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        if (validasiInput2()==true){
            txt_terimakasih1.setText("Mohon Tunggu Sedang Di Proses");
            dateday0();
            dateday1();
             AllDataOpenIT();
             AllDataOpenCC();
                ExportCCForm();
                ExportITForm();
               txt_terimakasih1.setText("Berhasil Di Proses");
                
            
        }
        
       
                // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked
 private void gambar(){
        List<TroubleEtModel> etModelsByDate2 = troubleETDao.getEtModelsByDate2(txt_tglawal.getDate(), txt_akhir.getDate());
        
         try {
            
        //Get the excel file.
        FileInputStream file = new FileInputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xls"));

        //Get workbook for XLS file.
        HSSFWorkbook yourworkbook = new HSSFWorkbook(file);;


        //Get first sheet from the workbook.
        //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
        HSSFSheet sheet1 = yourworkbook.getSheetAt(0);
        
      
        
            Row row = sheet1.getRow(0);
             org.apache.poi.ss.usermodel.Cell columnday = row.getCell(0);
           byte[] byteArray = yourworkbook.getBytes();
           InputStream is = new ByteArrayInputStream(byteArray);
               byteArray=(etModelsByDate2.get(0).getPicbefore());
             
             
             
       
        file.close();
        //Where you want to save the updated sheet.
        FileOutputStream out = 
            new FileOutputStream(new File("E:/FORM HARIAN IT & CALL CENTER/Form Call Center & IT Support Unit.xls"));
        yourworkbook.write(out);
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
        }
    
    
 
 
 
 
    
 
 
 
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser txt_akhir;
    private javax.swing.JTextField txt_petugas;
    private javax.swing.JLabel txt_terimakasih1;
    private com.toedter.calendar.JDateChooser txt_tglawal;
    // End of variables declaration//GEN-END:variables
}
