/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ridwan.Frm;

import TableModelHeadercheckBox.TableHeaderCheckBox;
import com.ridwan.DAO.UserDAo;
import com.ridwan.Dialog.DialogAddUser;
import com.ridwan.Dialog.DialogEditUser;
import com.ridwan.Model.UserModel;
import com.ridwan.TableModel.TableModelUser;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ciwong
 */
public class UserFrm extends javax.swing.JInternalFrame implements DocumentListener{
    
     private TableModelUser  tableModelUser = new TableModelUser();
     private UserDAo userDAo = new UserDAo();
     private TableRowSorter rowSorter = new TableRowSorter();
     
     

    /**
     * Creates new form UserFrm
     */
    public UserFrm() {
        initComponents();
        setTitle("Data User");
        tabel_user.setModel(tableModelUser);
        loadData();
        setClosable(true);
        setIconifiable(true);
        tabel_user.setModel(tableModelUser);
         //tabel_user.getColumnModel().getColumn(5).setHeaderRenderer(new TableHeaderCheckBox(tabel_user.getTableHeader(), 5));
        loadData();
         rowSorter = new TableRowSorter(tabel_user.getModel());
        tabel_user.setRowSorter(rowSorter);
        txt_Cari.getDocument().addDocumentListener(this);
    }
    
    private void loadData(){
         List<UserModel> userModels = userDAo.getUserModels();
         tableModelUser.setData(userModels);
    }
    
    
      private void saring(){
        String text = txt_Cari.getText();
        if (text.length()==0){
            rowSorter.setRowFilter(null);
        }else {
           rowSorter.setRowFilter(RowFilter.regexFilter
        (Pattern.compile("(?i).*" + text + ".*", Pattern.CASE_INSENSITIVE|Pattern.DOTALL ).toString()));
        }
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_user = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();

        tabel_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_user);

        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/Add_24x24.png"))); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel2.add(btntambah);

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/Edit_24x24.png"))); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        jPanel2.add(btnubah);

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ridwan/ICON/Remove_24x24.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnhapus);

        jLabel1.setText("Cari :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
List<UserModel> CekUSer = tableModelUser.getUsercek();
if (!CekUSer.isEmpty()){
   if (JOptionPane.showConfirmDialog(null, "Konfirmasi", "Apakah Anda Ingin Menghapus Data Ini ?", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
    boolean valid = true;
    for (UserModel userModel : CekUSer){
        if (valid){
            userDAo.deleteUser(userModel);
        }
        loadData();
    }
    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
}
}else {
    JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
DialogAddUser dialogAddUser = new DialogAddUser();
UserModel insertuser = dialogAddUser.insertUser();
if (userDAo.insertUser(insertuser)==true){
    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
    loadData();
}else {
    JOptionPane.showMessageDialog(null, "Data Gagal disimpan");

loadData();
}

// TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
int index = tabel_user.getSelectedRow();
if (index!=-1){
    UserModel user = tableModelUser.getUser(tabel_user.convertColumnIndexToModel(index));
    DialogEditUser d = new DialogEditUser();
    UserModel um = d.updateUser(user);
    if (um!=null){
        userDAo.updateUser(um);
        tableModelUser.updateUser(index, um);
        loadData();
    }
}else {
        JOptionPane.showMessageDialog(null, "Seleksi Salah Satu Baris");
    }

// TODO add your handling code here:
    }//GEN-LAST:event_btnubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_user;
    private javax.swing.JTextField txt_Cari;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        saring();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        saring();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    saring();
    }
}
